# Advent of code 2023
https://adventofcode.com/2023/

# Day 1


## Part 1
Your puzzle answer was 55123.

In [1]:
from io import StringIO

inputstr = """1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet
"""
testinput = StringIO(inputstr)


def get_cal(s):
    for c in s:
        if c.isdigit():
            f = c
            break
    for c in s[::-1]:
        if c.isdigit():
            l = c
            break
    return int(f + l)


f = open("1_input.txt")
# f = testinput
sum_cal = 0
for l in f:
    # print(l, get_cal(l))
    sum_cal += get_cal(l)
print(sum_cal)
f.close()

55123


## Part 2
Your puzzle answer was 55260.

In [2]:
from io import StringIO

inputstr = """two1nine
eightwothree
abcone2threexyz
xtwone3four
4nineeightseven2
zoneight234
7pqrstsixteen
"""
testinput = StringIO(inputstr)

digits = {
    "one": "1",
    "two": "2",
    "three": "3",
    "four": "4",
    "five": "5",
    "six": "6",
    "seven": "7",
    "eight": "8",
    "nine": "9",
}


def isdigit(s, reverse=False):
    if s[0].isdigit():
        return s[0]
    for k, v in digits.items():
        if (not reverse and s.startswith(k)) or (reverse and s.startswith(k[::-1])):
            return v
    return None


def get_cal(s):
    s_rev = s[::-1]
    for i in range(len(s)):
        if v := isdigit(s[i:]):
            f = v
            break
    for i in range(len(s_rev)):
        if v := isdigit(s_rev[i:], True):
            l = v
            break
    return int(f + l)


f = open("1_input.txt")
# f = testinput
sum_cal = 0
for l in f:
    # print(l, get_cal(l))
    sum_cal += get_cal(l)
print(sum_cal)
f.close()

55260


# Day 2
https://adventofcode.com/2023/day/2

## Part 1
Your puzzle answer was 2169.

In [3]:
from collections import defaultdict
from io import StringIO

inputstr = """Game 1: 3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green
Game 2: 1 blue, 2 green; 3 green, 4 blue, 1 red; 1 green, 1 blue
Game 3: 8 green, 6 blue, 20 red; 5 blue, 4 red, 13 green; 5 green, 1 red
Game 4: 1 green, 3 red, 6 blue; 3 green, 6 red; 3 green, 15 blue, 14 red
Game 5: 6 red, 1 blue, 3 green; 2 blue, 1 red, 2 green
"""
testinput = StringIO(inputstr)

f = open("2_input.txt")
# f = testinput
possibles = []
i = 1
for l in f:
    cd = defaultdict(int)
    id = i
    l = l[l.find(":") + 1 :]
    sets = l.split(";")
    for s in sets:
        cubes = s.strip().split(",")
        for cube in cubes:
            n, c = cube.strip().split(" ")
            cd[c] = max(cd[c], int(n))
    i += 1
    if cd["red"] <= 12 and cd["green"] <= 13 and cd["blue"] <= 14:
        possibles.append(id)

print(sum(possibles))
f.close()

2169


## Part 2
Your puzzle answer was 60948.

In [4]:
from collections import defaultdict
from io import StringIO

inputstr = """Game 1: 3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green
Game 2: 1 blue, 2 green; 3 green, 4 blue, 1 red; 1 green, 1 blue
Game 3: 8 green, 6 blue, 20 red; 5 blue, 4 red, 13 green; 5 green, 1 red
Game 4: 1 green, 3 red, 6 blue; 3 green, 6 red; 3 green, 15 blue, 14 red
Game 5: 6 red, 1 blue, 3 green; 2 blue, 1 red, 2 green
"""
# testinput = StringIO(inputstr)
# f = testinput
f = open("2_input.txt")


possibles = []
power = 0
i = 1
for l in f:
    cd = defaultdict(int)
    id = i
    l = l[l.find(":") + 1 :]
    sets = l.split(";")
    for s in sets:
        cubes = s.strip().split(",")
        for cube in cubes:
            n, c = cube.strip().split(" ")
            cd[c] = max(cd[c], int(n))
    i += 1
    power += cd["red"] * cd["green"] * cd["blue"]

print(power)
f.close()

60948


# Day 3

## Part 1
Your puzzle answer was 498559.

In [5]:
import re
from io import StringIO
from itertools import product

#ans: 4361
inputstr = """467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
"""
testinput = StringIO(inputstr)


# f = open("3_input.txt")
f = testinput


def get_par_locs(schema, m, n):
    part_locs = [[0 for _ in range(n)] for _ in range(m)]
    for i, j in product(range(m), range(n)):
        if schema[i][j].isdigit() or (schema[i][j] == "."):
            continue
        for x, y in product([-1, 0, 1], [-1, 0, 1]):
            if 0 <= i + x < m and 0 <= j + y < n:
                part_locs[i + x][j + y] = 1  # 0 [0][0] won't be a problem
    return part_locs


schema = [l.strip() for l in f.readlines()]
m = len(schema)
n = len(schema[0])

part_locs = get_par_locs(schema, m, n)
numbers = []
for i, l in enumerate(schema):
    for match in re.finditer("[\d]+", l):
        for j in range(int(match.span()[0]), int(match.span()[1])):
            if part_locs[i][j]:
                numbers.append(int(match.group(0)))
                break


print(sum(numbers))

4361


## Part 2
Your puzzle answer was 72246648.

In [6]:
from itertools import product
from io import StringIO
from collections import defaultdict
import re

#ans: 467835
inputstr = """467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
"""
testinput = StringIO(inputstr)



f = open("3_input.txt")
# f = testinput

def get_par_locs(schema, m, n):
    part_locs = [[0 for _ in range(n)] for _ in range(m)]
    star_id = 1
    for i, j in product(range(m), range(n)):
        if schema[i][j] != "*":
            continue
        for x, y in product([-1, 0, 1], [-1, 0, 1]):
            if 0 <= i + x < m and 0 <= j + y < n:
                part_locs[i + x][j + y] = star_id  # 0 [0][0] won't be a problem
        star_id +=1
    return part_locs


schema = [l.strip() for l in f.readlines()]
m = len(schema)
n = len(schema[0])

part_locs = get_par_locs(schema, m, n)

numbers = defaultdict(list)
for i, l in enumerate(schema):
    for match in re.finditer('[\d]+', l):
        for  j in range(int(match.span()[0]), int(match.span()[1])):
            if star_id := part_locs[i][j]:
                    numbers[star_id].append(int(match.group(0)))
                    break


gear_ratio = 0 
for g, possible_gear in numbers.items():
    if len(possible_gear)==2:
        gear_ratio += possible_gear[0] * possible_gear[1]
print(gear_ratio)

72246648


# Day 4

## Part 1:
Your puzzle answer was 26346

In [7]:
from io import StringIO
import re

inputstr = """Card 1: 41 48 83 86 17 | 83 86  6 31 17  9 48 53
Card 2: 13 32 20 16 61 | 61 30 68 82 17 32 24 19
Card 3:  1 21 53 59 44 | 69 82 63 72 16 21 14  1
Card 4: 41 92 73 84 69 | 59 84 76 51 58  5 54 83
Card 5: 87 83 26 28 32 | 88 30 70 12 93 22 82 36
Card 6: 31 18 13 56 72 | 74 77 10 23 35 67 36 11
"""
testinput = StringIO(inputstr)
f = open("4_input.txt")
# f = testinput


lines = [l.strip() for l in f.readlines()]
points = 0
for l in lines:
    win, have = l.split('|')
    _, win = win.split(':')
    win = re.split('\s+', win.strip())
    have = re.split('\s+', have.strip())
    win_num = [1 for h in have if h in win]    
    if win_num:
        points += 2 ** (len(win_num)-1)
print(points)

26346


## Part 2
Your puzzle answer was 8467762

In [19]:
import re
from collections import defaultdict
from io import StringIO

inputstr = """Card 1: 41 48 83 86 17 | 83 86  6 31 17  9 48 53
Card 2: 13 32 20 16 61 | 61 30 68 82 17 32 24 19
Card 3:  1 21 53 59 44 | 69 82 63 72 16 21 14  1
Card 4: 41 92 73 84 69 | 59 84 76 51 58  5 54 83
Card 5: 87 83 26 28 32 | 88 30 70 12 93 22 82 36
Card 6: 31 18 13 56 72 | 74 77 10 23 35 67 36 11
"""
testinput = StringIO(inputstr)
f = open("4_input.txt")
# f = testinput


lines = [l.strip() for l in f.readlines()]
cards = [1] * len(lines)
for card_num, l in zip(range(len(lines)), lines):
    win, have = l.split('|')
    _, win = win.split(':')
    win = re.split('\s+', win.strip())
    have = re.split('\s+', have.strip())
    win_num = [1 for h in have if h in win]    
    for i in range(card_num+1, card_num + len(win_num)+1):
        cards[i] += cards[card_num]

print(sum(cards))

8467762


# Day 5

## Part1
Your puzzle answer was 31599214.


In [9]:
from io import StringIO
import re
from collections import defaultdict

inputstr = """seeds: 79 14 55 13

seed-to-soil map:
50 98 2
52 50 48

soil-to-fertilizer map:
0 15 37
37 52 2
39 0 15

fertilizer-to-water map:
49 53 8
0 11 42
42 0 7
57 7 4

water-to-light map:
88 18 7
18 25 70

light-to-temperature map:
45 77 23
81 45 19
68 64 13

temperature-to-humidity map:
0 69 1
1 0 69

humidity-to-location map:
60 56 37
56 93 4
"""
testinput = StringIO(inputstr)



f = open("5_input.txt")
# f = testinput


lines = [l.strip() for l in f.readlines()]

# read_map
seed_map = defaultdict(lambda : defaultdict(list))
seed_map = dict()
state = 'read_seeds'
for l in lines:
    if l=='':
        if state == 'start':
            state='read_seeds'
        elif state == 'read_seeds':
            state = 'find_map'
        elif state == 'find_map':
            state = 'read_map'
        elif state == 'read_map':
            state = 'find_map'
        continue
    if state == 'read_seeds' and l.startswith('seeds:'):
        seeds = l.split(':')[1].strip().split(' ')    
        seeds = [int(s) for s in seeds]
        continue
    if state == 'find_map' and l.endswith('map:'):
        source, dest = l.split(' ')[0].split('-to-')
        seed_map[source] = ({'dest': dest, 'map':[]})
        state = 'read_map'
        continue        
        
    if state == 'read_map' :
        map_entry = l.split()
        map_entry = [int(i) for i in map_entry]
        seed_map[source]['map'].append(map_entry)
        continue
        
def get_index(map_entry, si):
    # map_rows = map_entry['map']
    for dest, src, w in map_entry:
        if src <=si< src+w:
            return dest + (si-src)
    return si

    
def find_loc(seed_map, source, source_index):
    while True:
        # print(source)
        source_index = get_index(seed_map[source]['map'], source_index)
        # print(source_index)
        source = seed_map[source]['dest'] 
        if source == 'location':
            return source_index

locs = [find_loc(seed_map, 'seed', s) for s in seeds]
print(min(locs))    


31599214


## Part 2
Your puzzle answer was 20358599

In [10]:
%%time
from io import StringIO
import re
from collections import defaultdict

inputstr = """seeds: 79 14 55 13

seed-to-soil map:
50 98 2
52 50 48

soil-to-fertilizer map:
0 15 37
37 52 2
39 0 15

fertilizer-to-water map:
49 53 8
0 11 42
42 0 7
57 7 4

water-to-light map:
88 18 7
18 25 70

light-to-temperature map:
45 77 23
81 45 19
68 64 13

temperature-to-humidity map:
0 69 1
1 0 69

humidity-to-location map:
60 56 37
56 93 4
"""
testinput = StringIO(inputstr)



f = open("5_input.txt")
# f = testinput


lines = [l.strip() for l in f.readlines()]

# read_map
seed_map = defaultdict(lambda : defaultdict(list))
seed_map = dict()
state = 'read_seeds'
for l in lines:
    if l=='':
        if state == 'start':
            state='read_seeds'
        elif state == 'read_seeds':
            state = 'find_map'
        elif state == 'find_map':
            state = 'read_map'
        elif state == 'read_map':
            state = 'find_map'
        continue
    if state == 'read_seeds' and l.startswith('seeds:'):
        seeds = l.split(':')[1].strip().split(' ')    
        seeds = [int(s) for s in seeds]
        continue
    if state == 'find_map' and l.endswith('map:'):
        source, dest = l.split(' ')[0].split('-to-')
        seed_map[source] = ({'dest': dest, 'map':[]})
        state = 'read_map'
        continue        
        
    if state == 'read_map' :
        map_entry = l.split()
        map_entry = [int(i) for i in map_entry]
        seed_map[source]['map'].append(map_entry)
        continue
        
def get_index(map_entry, si):
    for dest, src, w in map_entry:
        if src <=si< src+w:
            return dest + (si-src)
    return si

# Reverse
reverse_seed_map = {
    v['dest']: {'dest': k, 'map': [[r[1], r[0], r[2]] for r in v['map']]}
    for k, v in seed_map.items()
}
def find_seed(seed_map, source, source_index):
    while True:
        # print(source)
        source_index = get_index(seed_map[source]['map'], source_index)
        # print(source_index)
        source = seed_map[source]['dest'] 
        if source == 'seed':
            return source_index

def seed_exist(reverse_seed_map, loc) :
    seed = find_seed(reverse_seed_map, 'location', loc)
    for i in range(0, len(seeds), 2):          
        s = seeds[i]
        w = seeds[i+1]
        if s<=seed < s+w:
            return True 
    return False

def get_min_loc(reverse_seed_map):
    loc = 1
    while True:
        if seed_exist(reverse_seed_map, loc):
            return loc
        loc +=1
        if loc % 1000000 == 0:
            print(loc)
print("**min=**", get_min_loc(reverse_seed_map))

1000000
2000000
3000000
4000000
5000000
6000000
7000000
8000000
9000000
10000000
11000000
12000000
13000000
14000000
15000000
16000000
17000000
18000000
19000000
20000000
**min=** 20358599
CPU times: user 4min 26s, sys: 552 ms, total: 4min 26s
Wall time: 4min 27s


# Day 6
## Part 1 and Part 2
Part1: Your puzzle answer was 219849.
Part: Your puzzle answer was 29432455.

In [22]:
%%time
import math
import re
from collections import defaultdict
from io import StringIO

import numpy

inputstr = """Time:      7  15   30
Distance:  9  40  200
"""
testinput = StringIO(inputstr)


f = open("6_input.txt")
# f = testinput

part = 2

lines = [l.strip() for l in f.readlines()]
times = re.split("\s+", lines[0].split(":")[1].strip())
records = re.split("\s+", lines[1].split(":")[1].strip())

if part == 1:
    times = [int(t) for t in times]
    records = [int(r) for r in records]

if part == 2:
    times = [int("".join(times))]
    records = [int("".join(records))]

margin = 1
for t, r in zip(times, records):
    x1 = (t - math.sqrt(t**2 - 4 * r)) / 2
    x2 = (t + math.sqrt(t**2 - 4 * r)) / 2
    lower = math.ceil(x1) if x1 != int(x1) else math.ceil(x1) + 1
    upper = math.floor(x2) if x2 != int(x2) else math.floor(x2) - 1
    margin *= upper - lower + 1
print(margin)

29432455
CPU times: user 762 µs, sys: 570 µs, total: 1.33 ms
Wall time: 923 µs


# Day 7
## Part 1
Your puzzle answer was 253603890.
## Part 2
Your puzzle answer was 253630098.

In [39]:
%%time
import math
import re
from collections import Counter
from io import StringIO

import numpy

inputstr = """32T3K 765
T55J5 684
KK677 28
KTJJT 220
QQQJA 483
"""
testinput = StringIO(inputstr)

part = 2
j_wild = False if part == 1 else True

f = open("7_input.txt")
# f = testinput

cards = ["A", "K", "Q", "J", "T", "9", "8", "7", "6", "5", "4", "3", "2"]

if j_wild:
    cards.remove("J")
    cards.append("J")
cards.reverse()
card_points = dict({c: r+1 for r, c in enumerate(cards)})

types = ["5", "1,4", "2,3", "1,1,3", "1,2,2", "1,1,1,2", "1,1,1,1,1"]
types.reverse()
type_points = dict({t: r+1 for r, t in enumerate(types)})

def gettype(hand, j_wild=False):
    j_count = 0
    c = Counter(hand)
    if j_wild: 
        j_count = c['J']
        del c['J']
    kinds = sorted(c.values())
    if kinds: 
        kinds[-1] += j_count
    else:
        kinds = [j_count]
    kinds = ",".join([str(i) for i in kinds])
    return type_points[kinds]
 
def get_hand_points(h, j_wild):
    h = list(h)
    h_points = [card_points[c] for c in h]
    return [gettype(h, j_wild)] + h_points    

hands = {}
for l in f.readlines():
    h, b = re.split("\s+", l.strip())
    hands[h] = int(b)

hands_sorted = sorted(hands.keys(), key=lambda h: get_hand_points(h, j_wild))
hands_ranks = {h:r+1 for r, h in enumerate(hands_sorted)}

winnings = 0
for h in hands:
    winnings += hands_ranks[h] * hands[h]
winnings

CPU times: user 9.49 ms, sys: 915 µs, total: 10.4 ms
Wall time: 9.64 ms


253630098

# Day 8
## Part 1
Your puzzle answer was 17621.

In [2]:
%%time
import math
import re
from collections import Counter
from io import StringIO

import numpy

inputstr = """LLR

AAA = (BBB, BBB)
BBB = (AAA, ZZZ)
ZZZ = (ZZZ, ZZZ)
"""
testinput = StringIO(inputstr)


f = open("8_input.txt")
# f = testinput
lines = f.readlines()
lines = [l.strip() for l in lines]
lines.remove('')
inst = lines[0]
nodes={}
for l in lines[1:]:
    m = re.match(r"(\w+)\s*=\s*\((\w+)\s*,\s*(\w+)\)", l)
    src, l, r = m.group(1), m.group(2), m.group(3)
    nodes[src] = [l,r]

inst = inst.replace('L', '0')
inst = inst.replace('R', '1')
inst = list(inst)
inst = [int(i) for i in inst]

current = 'AAA'
steps = 0
d = 0
while current != 'ZZZ':
    current = nodes[current][inst[d]]
    d = (d + 1) % len(inst)
    steps += 1
print(steps)  

17621
CPU times: user 40.3 ms, sys: 0 ns, total: 40.3 ms
Wall time: 40.3 ms


# Par 2
Your puzzle answer was 20685524831999.

In [3]:
%%time
import re
from io import StringIO
import math
import numpy

inputstr = """LR

11A = (11B, XXX)
11B = (XXX, 11Z)
11Z = (11B, XXX)
22A = (22B, XXX)
22B = (22C, 22C)
22C = (22Z, 22Z)
22Z = (22B, 22B)
XXX = (XXX, XXX)
"""
testinput = StringIO(inputstr)


f = open("8_input.txt")
# f = testinput
lines = f.readlines()
lines = [l.strip() for l in lines]
lines.remove('')
inst = lines[0]
nodes={}
for l in lines[1:]:
    m = re.match(r"(\w+)\s*=\s*\((\w+)\s*,\s*(\w+)\)", l)
    src, l, r = m.group(1), m.group(2), m.group(3)
    nodes[src] = [l,r]

inst = inst.replace('L', '0')
inst = inst.replace('R', '1')
inst = list(inst)
inst = [int(i) for i in inst]


current_nodes = [n for n in nodes if n.endswith('A')]
all_steps = []
for c in current_nodes:
    current = c
    steps = 0
    d = 0
    while not current.endswith('Z'):
        current = nodes[current][inst[d]]
        d = (d + 1) % len(inst)
        steps += 1
    all_steps.append(steps) 
print(math.lcm(*all_steps))

20685524831999
CPU times: user 387 ms, sys: 0 ns, total: 387 ms
Wall time: 420 ms


# Day 9
Part 1: Your puzzle answer was 1772145754.

Part 2: Your puzzle answer was 867.

In [4]:
%%time
import math
import re
from collections import Counter
from io import StringIO
import numpy as np

import numpy

inputstr = """0 3 6 9 12 15
1 3 6 10 15 21
10 13 16 21 30 45
"""
testinput = StringIO(inputstr)


f = open("9_input.txt")
# f = testinput
lines = f.readlines()
lines = [l.strip() for l in lines]

part = 2
if part == 1:
    index = -1
else:
    index = 0
def extrapolate(seq):
    seq_heads = []
    sign = 1
    while np.any(seq):
        seq_heads.append(sign * seq[index])
        seq = seq[1:] - seq[:-1]
        if part ==2: 
            sign = -1 * sign
    return np.sum(seq_heads)

sum_extra = 0
for l in lines:
    seq = re.split("\s+", l)
    seq = np.array([int(s) for s in seq])
    sum_extra += extrapolate(seq)
print(sum_extra)

867
CPU times: user 99.6 ms, sys: 0 ns, total: 99.6 ms
Wall time: 109 ms


# Day 10
Your puzzle answer was 6882.

Your puzzle answer was 491.

**The examples for part II are misleading, some of them have multiple loop connected to S, which shouldn't be the case**


In [1]:
%%time
import math
import re
from collections import Counter
from io import StringIO
from collections import defaultdict
from itertools import product

import numpy as np
np.set_printoptions(precision=0, suppress=True, linewidth=100)

# inputstr = """-L|F7
# 7S-7|
# L|7||
# -L-J|
# L|-JF
# """
inputstr = """7-F7-
.FJ|7
SJLL7
|F--J
LJ.LJ
"""

testinput = StringIO(inputstr)


f = open("10_input.txt")
# f = testinput
lines = f.readlines()
lines = [l.strip() for l in lines]

matrix = np.array([np.array(list(l)) for l in lines])
M, N = matrix.shape

def get_neighbors(current, c):
    i, j = current
    if c == '|':
        prev, next = (i-1, j), (i+1, j) 
    elif c == '-':
        prev, next = (i, j-1), (i, j+1)
    elif c ==  'L' :
        prev, next = (i-1, j), (i, j+1)
    elif c == 'J':
        prev, next = (i-1, j), (i, j-1)
    elif c == '7':
        prev, next = (i, j-1), (i+1, j)
    elif c == 'F':
        prev, next = (i, j+1), (i+1, j) 
    else:
        prev, next = (-1,-1), (-1,-1)
    return prev, next

def connect_with_neighbors(adj, current, c):
    prev, next = get_neighbors(current, c)
    if  (0 <= prev[0] < M and 0 <= prev[1] < N and
        0 <= next[0] < M and 0 <= next[1] < N):  
        adj[current] = [prev, next]
    

def get_adjacency(matrix):
    adj = {}
    for p in product(range(M), range(N)):
        connect_with_neighbors(adj, p, matrix[p])    
    return adj

def get_next(adj, prev, current):
    if current not in adj:
        return None
    if adj[current][0] == prev:
        return adj[current][1]
    if adj[current][1] == prev:
        return adj[current][0]
    return None 
        
        
def find_loop(adj, start):
    if start not in adj:
        return None
    loop = -1 * np.ones((M,N))
    pre_start = adj[start][0]
    prev, current  = pre_start, start
    pos = 0
    while True:
        loop[current] = pos
        if current == pre_start:
            return loop
        next = get_next(adj, prev, current)  
            
        if (not next or loop[next] > -1):
            # display(loop)
            return None
        prev, current = current, next
        pos += 1      
        
def guess_loop(matrix):
    adj = get_adjacency(matrix)
    s_pos = np.where(matrix == 'S')
    start = s_pos[0][0], s_pos[1][0]
    for c in ['|', '-', 'L', 'J', '7', 'F']: 
        adjcopy = adj.copy()
        connect_with_neighbors(adjcopy, start, c)    
        loop = find_loop(adjcopy, start)
        if loop is not None:
            matrix = matrix.copy()
            matrix[start] = c
            return matrix, loop
    return None, None
    
def reset_num(loop):
    loop_len = np.max(loop) + 1
    for p in product(range(M), range(N)):
        loop[p] = min(loop[p], loop_len - loop[p])

def find_enclosed(matrix, loop):
    schema = matrix.copy()
    for p in product(range(M), range(N)):
        if loop[p] == -1:
            schema[p] = 'X'            
    
    for i in range(M):
        s = 'O'
        for j in range(N):
            if schema[(i, j)] == 'X':
                schema[(i,j)] = s
            elif schema[(i, j)] in ['L', 'J', '|']:
                s = 'I' if s == 'O' else 'O'
    return schema, np.count_nonzero(np.where(schema.flatten()=='I'))   

print("input:\n")        
print(matrix)
matrix_masked, loop = guess_loop(matrix)
print("\ninput, only loop:\n")
print(matrix_masked)
print("\nloop:\n")
print(loop)
reset_num(loop)
furthest = int(np.max(loop))
print("\nPart1: ", furthest)

nest_map, num_enclosed = find_enclosed(matrix_masked, loop)
print("\nnest map:\n")
print(nest_map)
print("\nPart 2: ", num_enclosed)

input:

[['7' '.' '7' ... '7' '7' '.']
 ['F' '-' 'F' ... '|' '-' '.']
 ['F' 'F' '-' ... '|' '|' '7']
 ...
 ['|' '|' '|' ... 'F' '-' '.']
 ['F' 'L' 'J' ... 'J' '.' 'F']
 ['F' 'J' '.' ... 'L' '|' '.']]

input, only loop:

[['7' '.' '7' ... '7' '7' '.']
 ['F' '-' 'F' ... '|' '-' '.']
 ['F' 'F' '-' ... '|' '|' '7']
 ...
 ['|' '|' '|' ... 'F' '-' '.']
 ['F' 'L' 'J' ... 'J' '.' 'F']
 ['F' 'J' '.' ... 'L' '|' '.']]

loop:

[[-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]]

Part1:  6882

nest map:

[['O' 'O' 'O' ... 'O' 'O' 'O']
 ['O' 'O' 'O' ... 'O' 'O' 'O']
 ['O' 'O' 'O' ... 'O' 'O' 'O']
 ...
 ['O' 'O' 'O' ... 'O' 'O' 'O']
 ['O' 'O' 'O' ... 'O' 'O' 'O']
 ['O' 'O' 'O' ... 'O' 'O' 'O']]

Part 2:  491
CPU times: user 266 ms, sys: 98.1 ms, total: 364 ms
Wall time: 244 ms


# Day 11
Part 1: Your puzzle answer was 10033566.

Part 2: Your puzzle answer was 560822911938.

In [3]:
%%time
import math
import re
from collections import Counter
from io import StringIO
from collections import defaultdict
from itertools import product

import numpy as np
np.set_printoptions(precision=0, suppress=True, linewidth=100)

inputstr = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
"""

testinput = StringIO(inputstr)


f = open("11_input.txt")
# f = testinput
lines = f.readlines()
lines = [l.strip() for l in lines]

matrix = np.array([np.array(list(l)) for l in lines])
M, N = matrix.shape    

part = 2
expand_factor = 2 if part==1 else 1000000
def shortest_path(x1, y1, x2, y2, empty_x, empty_y):
        x1, x2 = sorted((x1, x2))
        y1, y2 = sorted((y1, y2))
        d = (x2 - x1) + abs(y2 - y1)
        e_x = sum((x1 < empty_x) & (empty_x < x2))
        e_y = sum((y1 < empty_y) & (empty_y < y2))
        return d + (expand_factor-1) * e_x + (expand_factor-1) * e_y
    

galaxies_x, galaxies_y = np.where(matrix=='#')
num_galaxies = len(galaxies_x)
empty_x = [i for i in range(M) if i not in galaxies_x]
empty_y = [i for i in range(N) if i not in galaxies_y]
sum_d = 0
for i in range(num_galaxies):
    for j in range(i+1, num_galaxies):
        sum_d += shortest_path(galaxies_x[i], galaxies_y[i], galaxies_x[j], galaxies_y[j], empty_x, empty_y)
        
print("sum_d: ", sum_d)

sum_d:  560822911938
CPU times: user 2.26 s, sys: 445 µs, total: 2.26 s
Wall time: 2.26 s


# Day 12
Your puzzle answer was 7633.

Your puzzle answer was 23903579139437


In [2]:
%%time

"""
printing out the arrangement for part 2 is impossible, commented out
"""
import math
import re
from collections import Counter
from io import StringIO
from collections import defaultdict
from itertools import product

import numpy as np
np.set_printoptions(precision=0, suppress=True, linewidth=100)

inputstr = """???.### 1,1,3
.??..??...?##. 1,1,3
?#?#?#?#?#?#?#? 1,3,1,6
????.#...#... 4,1,1
????.######..#####. 1,6,5
?###???????? 3,2,1
"""

testinput = StringIO(inputstr)


f = open("12_input.txt")
# f = testinput
lines = f.readlines()
lines = [l.strip() for l in lines]



def count_single(conds, n): 
        
    results = []
    for i in range(len(conds)):
            head, tail, last = conds[:i], conds[i:i+n], conds[i+n:i+n+1] 
            last = '.' if last == '?' else last
        
            if ('#' in head) or (len(tail) < n):
                break  
            if ('.' not in tail) and (last != '#'):
                # results.append((i+n+1,'.'*len(head) + '#'*n + last))
                results.append(i+n+1)

    return results

function_call = 0
def count_multiple(conds, conds_index, numbers, numbers_index, dptable):
    if (conds_index, numbers_index) in dptable:
        return dptable[(conds_index, numbers_index)]
    # print(f"count_multiple: {conds}, {conds_index}, {numbers}, {numbers_index}")
    global function_call
    function_call += 1
    current_numbers = numbers[numbers_index:]
    current_conds = conds[conds_index:]
    if not current_numbers:
        if '#' in current_conds:
            # results = []
            results = 0
        else:
            # results = ['.' * len(current_conds)]   
            results = 1   
    else:    
        n = current_numbers[0]
        n_results = count_single(current_conds, n)
        results = []
        results = 0
        # for i, r in n_results:
        for i in n_results:
            rest_results = count_multiple(conds, i+conds_index, numbers, numbers_index+1, dptable)
            # results  += [r+y  for y in  rest_results]  
            results  +=  rest_results  
    dptable[(conds_index, numbers_index)]  = results
    return results

def count_multiple_driver(conds, numbers):
    dptable = {}
    return count_multiple(conds, 0, numbers, 0, dptable)

def prepare_input(line, folds):
    conds, numbers = l.split(' ')
    conds = re.sub('\.+', '.', conds)
    conds = "?".join ([conds] * folds)
    conds += '.' 

    numbers = ",".join([numbers] * folds)
    numbers = [int(i) for i in numbers.split(',')]
    
    return conds, numbers

part = 2
folds = 1 if part == 1 else 5
count = 0



num_lines = len(lines)
for i, l in enumerate(lines):
    # print (f"line {i} (out of {num_lines})")
    conds, numbers = prepare_input(l, folds)
    arrangements = count_multiple_driver(conds, numbers)  
    # print (f"{l}: {len(arrangements)} arrangements")
    # count += len(arrangements)
    count += arrangements
    
print(count)
print(function_call)




23903579139437
169530
CPU times: user 1.18 s, sys: 0 ns, total: 1.18 s
Wall time: 1.18 s
